### ISSUE TITLE
Support for the second apply (when output files generated and not there anymore)

### ISSUE THREAD

**Issue by JPLachance** [matti/terraform-shell-resource#1]
First of all, thanks for sharing that module! It's helping me a lot to understand how I could run a shell command and get its output. 😄 

I am trying to generate a key using the `openssl rand -hex 16`.  I found your module and I tried it:
```
module "openssl_rand_key" {
  source  = "matti/resource/shell"
  version = "0.3.2"

  command = "openssl rand -hex 16"
}
```

It works perfectly the first time I run the `terraform apply` command. My problem is when I try to run the `terraform apply` a second time, the stdout file isn't generated so the `data "local_file" "stdout"` resource is not able to open the file. This is partly caused by the fact my `terraform apply` command is being run in a sandbox and files created on the fly are not persisted. For example, if Jenkins runs the `terraform apply` command in a job A then tries to run it again in a job B, it won't work.

Obviously, I don't want to commit the result of `openssl rand -hex 16` in my source code repository!

I also tried your [other module](https://github.com/matti/terraform-shell-outputs), but that one is generating a new random key at each `apply`.

So, what would you do in that case? My other solution is to create a custom `"null_resource"` with a `provisioner` that runs the `openssl rand -hex 16` command and stores the result in a vault.

Thanks for your help!

**Comment by matti** [comment]
@JPLachance sorry for the late reply, I missed this. 

I realized this too - my current workaround is to write the stoud/stderr files to another directory and then persist those.. (not pushed yet). Maybe you could sync the module directory somewhere and restore it before the apply (horrible, I know)..

Could you share more on the result storing in vault, it sounds interesting but I'm not sure what you mean with that?

**Comment by matti** [comment]
I might have solved this with a horrible hack - getting too drunk to verify it fully, let's see tomorrow if I need to drink more or not.

**Comment by matti** [comment]
@JPLachance wow my insane trick worked! https://github.com/matti/terraform-shell-resource/blob/master/main.tf#L58-L67

Just released 0.4.0 with this trick.

the bad news is that now you need ruby to be installed - I don't have time to write the reader in shell script now.

**Comment by JPLachance** [comment]
Good morning @matti! Your hack is working! Here is an example of what I was trying to do:
```
module "openssl_rand_key" {
  source  = "matti/resource/shell"
  version = "0.4.0"

  command = "openssl rand -hex 16"
}

resource "aws_ssm_parameter" "some_ssm_secured_parameter" {
  name  = "/some/ssm/secured/parameter"
  type  = "SecureString"
  value = "${module.openssl_rand_key.stdout}"
}
```

And now, here is the console output when I run `terraform apply` for the first time:
```shell
module.openssl_rand_key.null_resource.start: Creating...
  triggers.%:          "" => "1"
  triggers.depends_id: "" => ""
module.openssl_rand_key.null_resource.start: Creation complete after 0s (ID: 5488474326286063975)
module.openssl_rand_key.null_resource.shell: Creating...
  triggers.%:      "" => "1"
  triggers.string: "" => ""
module.openssl_rand_key.null_resource.shell: Provisioning with 'local-exec'...
module.openssl_rand_key.null_resource.shell (local-exec): Executing: ["/bin/sh" "-c" "openssl rand -hex 16 2>\"/var/tgf/terragrunt/rdYV6G36qHErk103_p2nSC5KKS0/2QqH8Bdc_R1vi24Bt7nH9yB2AGY/.terraform/modules/93db91de164d6f0180919202e57234c3/matti-terraform-shell-resource-e9cb317/stderr.2839409698889221245\" >\"/var/tgf/terragrunt/rdYV6G36qHErk103_p2nSC5KKS0/2QqH8Bdc_R1vi24Bt7nH9yB2AGY/.terraform/modules/93db91de164d6f0180919202e57234c3/matti-terraform-shell-resource-e9cb317/stdout.2839409698889221245\"; echo $? >\"/var/tgf/terragrunt/rdYV6G36qHErk103_p2nSC5KKS0/2QqH8Bdc_R1vi24Bt7nH9yB2AGY/.terraform/modules/93db91de164d6f0180919202e57234c3/matti-terraform-shell-resource-e9cb317/exitstatus.2839409698889221245\""]
module.openssl_rand_key.null_resource.shell: Creation complete after 0s (ID: 2839409698889221245)
module.openssl_rand_key.data.external.read: Refreshing state...
module.openssl_rand_key.null_resource.contents: Creating...
  triggers.%:          "" => "3"
  triggers.exitstatus:
           1 0 
  triggers.stderr:     "" => ""
  triggers.stdout:    
           1 e8281ada654b21a6493188273708d826 
module.openssl_rand_key.null_resource.contents: Creation complete after 0s (ID: 7481258853689841477)
aws_ssm_parameter.some_ssm_secured_parameter: Creating...
  arn:    "" => "<computed>"
  key_id: "" => "<computed>"
  name:   "" => "/some/ssm/secured/parameter"
  type:   "" => "SecureString"
  value:  "<sensitive>" => "<sensitive>"
aws_ssm_parameter.some_ssm_secured_parameter: Creation complete after 0s (ID: /some/ssm/secured/parameter)
```

And now, on the second `apply`, it's not breaking anymore and it's not generating a new random key each time! Perfect! 🎉 

My only concern now is the fact the key got printed in the console output 😄  
```shell
  triggers.stdout:    
           1 e8281ada654b21a6493188273708d826
```

Being able to tag the `stdout` output "sensitive" and therefore hiding it in the Terraform console output would be awesome! Why? Because in my case, the `terraform apply` command is being run by Jenkins and I don't want the Jenkins console output to contain sensitive values.

In any case, great work! Your module is allowing anyone to get and store the result of any command without having to code a custom Terraform resource in a custom provider. Thanks for that! 👍

**Comment by matti** [comment]
@jplachance sensitive filtering is not possible with modules no matter how many beers I would drink. what you could do in your use case is just to redirect terraform apply output to a file to exclude it from jenkins. Or pipe and replace some of the output with sed etc.

**Comment by JPLachance** [comment]
Alright! Thanks for your help! 😃

**Comment by matti** [comment]
@JPLachance just pushed a version without the need for ruby. Sensitive filtering is coming in https://github.com/hashicorp/terraform/issues/17568
