### ISSUE TITLE
Failing in terraform version 0.11.10

### ISSUE THREAD

**Issue by alikini** [matti/terraform-shell-resource#16]
Hello , 
We facing this error with last version of your module:

Error downloading modules: Error loading modules: module redis_db: Error parsing .terraform/modules/386b783cae42cc5d35e04ba26653f35b/matti-terraform-shell-resource-a39ec5f/main.tf: At 11:18: Unknown token: 11:18 IDENT var.depends_id

Thank you !

**Comment by tcavalca** [comment]
I don't think latest version is backward compatible with terraform v0.11.x
adding a version constraint should solve:
```module "master_node" {
 source = "matti/resource/shell"
 version = "v0.6.0"
```
tenorio

**Comment by matti** [comment]
terraform modules can not be backwards compatible, sorry
