### ISSUE TITLE
Non-self references in destroy-time provisioners issue on TF 0.12

### ISSUE THREAD

**Issue by seboudry** [matti/terraform-shell-resource#17]
Hi !

Terraform 0.12 seems to have a better cycle verification system that breaks `matti/resource/shell` module "hacking" behaviour.
Don't know if something can be done to comply with it.

### Example

Example:
```tf
module "temp" {
  source  = "matti/resource/shell"
  version = "0.12"
  command = "ls -la"
}
```

### Error on module deletion

Go some error when deleting an existing instance of module.
After deleting previous example block and running `terrafom plan` or `apply`:
```
Error: Provider configuration not present

To work with module.temp.null_resource.contents its original provider
configuration at module.temp.provider.null is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy module.temp.null_resource.contents, after which you
can remove the provider configuration again.
```
Same message for `null_resource.contents`, `data.external.exitstatus`, `data.external.stderr`, `null_resource.start`, `data.external.stdout`, `null_resource.shell`.

### Deletion Workaround

Remove every reference of instance module on Terraform state:
```
terraform state list | grep module.temp | xargs terraform state rm
```

Remove by hand every file/resource created by module `command`.

### Deprecation warning

Moreover, with Terraform 0.12.18 they introduce a deprecation notice about non-self references in destroy-time provisioners.

> UPGRADE NOTES:
> Inside provisioner blocks that have when = destroy set, and inside any connection blocks that are used by such provisioner blocks, it is now deprecated to refer to any objects other than self, count, and each.
> Terraform has historically allowed this but doing so tends to cause downstream problems with dependency cycles or incorrect destroy ordering because it causes the destroy phase of one resource to depend on the existing state of another. Although this is currently only a warning, we strongly suggest seeking alternative approaches for existing configurations that are hitting this warning in order to avoid the risk of later problems should you need to replace or destroy the related resources.
> This deprecation warning will be promoted to an error in a future release.
> 
> ENHANCEMENTS:
> provisioners: Warn about the deprecation of non-self references in destroy-time provisioners, both to allow preparation for this later becoming an error and also as an extra hint for the "Cycle" errors that commonly arise when such references are used. (#23559)
>
> https://github.com/hashicorp/terraform/releases/tag/v0.12.18

With previous example, ouptut of `plan` or `apply` show this message:
```
Warning: External references from destroy provisioners are deprecated

  on .terraform/modules/temp/matti-terraform-shell-resource-a39ec5f/main.tf line 31, in resource "null_resource" "shell":
  31:     command = local.command_when_destroy_chomped == "" ? ":" : local.command_when_destroy_chomped

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.

(and 7 more similar warnings elsewhere)
```

### Terraform version

```
$ terraform version
Terraform v0.12.18
+ provider.external v1.2.0
+ provider.null v2.1.2
```

**Comment by userhas404d** [comment]
Not sure about your state issue but the 'non-self references in destroy-time provisioners' warning is being tracked here: https://github.com/hashicorp/terraform/issues/23679

**Comment by matti** [comment]
This should now be fixed
