### ISSUE TITLE
Environment variables are not supported

### ISSUE THREAD

**Issue by nmiodice** [matti/terraform-shell-resource#18]
I'd like to pass TF configuration (tf vars) though to my command (which is a complex script that relies on ENV vars), but am unable to do so because there is no ability to pass environment vars.

**Comment by matti** [comment]
can you give me a more concrete example?

**Comment by nmiodice** [comment]
I'd like to run something like this:
```hcl
module "files" {
  source  = "matti/resource/shell"
  command = "echo $FOO"
  environment = {
    FOO       = var.foo
  }
}
```

Of course, the actual business logic in the script is more complex and relies on a number of environment variables. Passing them in as arguments may be complicated as I'd need to also handle escape characters

**Comment by matti** [comment]
environment variables are supported now, see the README
