### ISSUE TITLE
Make module easier to find by adding description to terraform registry

### ISSUE THREAD

**Issue by nitrocode** [matti/terraform-shell-resource#24]
This module only comes up when searching `shell` in the registry but it doesn't come up when searching `command`. I was fortunate to find this module by googling for it.

Found shell-outputs but not shell-resource: https://registry.terraform.io/search?q=shell
Found neither: https://registry.terraform.io/search?q=command

This module doesn't have `command` in its title and it can be found on the registry because that keyword is in its description.

https://registry.terraform.io/modules/amancevice/slackbot-group-sms/aws

Current tf registry link: https://registry.terraform.io/modules/matti/resource/shell
Older tf tegistry link to different repo?: https://registry.terraform.io/modules/matti/outputs

**Comment by matti** [comment]
agreed, how do I write the description :D

**Comment by nitrocode** [comment]
Looks like if you provide the description in the github repo at the top, it will be scraped by the registry. I'm assuming this based on the repo [amancevice/terraform-aws-slackbot-group-sms](https://github.com/amancevice/terraform-aws-slackbot-group-sms) because it's description at the top matches its description in the [terraform registry](https://registry.terraform.io/modules/amancevice/slackbot-group-sms/aws/0.0.1). I don't have any of my own modules to be able to login to the registry to test it.

**Comment by matti** [comment]
Thanks added all kinds of words there https://registry.terraform.io/modules/matti/resource/shell/1.0.2
