### ISSUE TITLE
Error when destroying resource

### ISSUE THREAD

**Issue by marrold** [matti/terraform-shell-resource#25]
Hi, when I attempt to delete a resource created with the terraform-shell-resource module by deleting the module block, I get the following error:

```
Error: Provider configuration not present

To work with
module.transit_gateway.module.create-transit-gateway-peering-attachment.null_resource.contents
its original provider configuration at
module.transit_gateway.module.create-transit-gateway-peering-attachment.provider.null
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.transit_gateway.module.create-transit-gateway-peering-attachment.null_resource.contents,
after which you can remove the provider configuration again
```

Am I doing something wrong?

Thanks

**Comment by matti** [comment]
I've noticed that this has started (?) to happen for me too with other modules too (when this module is not present)

As a workaround you could taint the module?

I've fixed other situations by introducing a vanity count to *all* resources like this

```
resource "something" "whatever" {
  count = var.enabled ? 1 : 0
}
```

and then set `enabled` to false, applied and then removed the module from code...

But I think the core issue is this: https://github.com/hashicorp/terraform/issues/22907#issuecomment-535580358

and this module has null provider for convenience in:
https://github.com/matti/terraform-shell-resource/blob/master/main.tf#L1-L3

so this module should remove that provider and then users of this module should add null provider when installing this module in their root module... 

(sidenote: terraform is a constant love/hate struggle... I thought 0.12 would be just awesome, and it is, but then you have new things like this...)

I'll think about this tomorrow.

**Comment by matti** [comment]
does this https://stackoverflow.com/a/60137302/161601 help now?

**Comment by matti** [comment]
Just released v1.0.3 - it should fix this - please try out and close if fixed

**Comment by matti** [comment]
or actually re-open :)

**Comment by marrold** [comment]
This is fixed, thanks 👍

**Comment by matti** [comment]
opened an issue in terraform: https://github.com/hashicorp/terraform/issues/24244
