### ISSUE TITLE
uuid doesn't get destroyed along with module

### ISSUE THREAD

**Issue by alextwlam-melco-resorts-com** [matti/terraform-shell-resource#28]
uuid doesn't get destroy along with module, resulting in error during re-run: 
```
Error: Invalid function argument

  on .terraform/modules/client_cert_arn/matti-terraform-shell-resource-7fffe89/main.tf line 104, in resource "null_resource" "contents":
 104:     stdout     = fileexists(local.stdout) ? chomp(file(local.stdout)) : lookup(null_resource.contents_if_missing.triggers, "stdout", "")
```

fix 
`terraform destroy --target=module.client_cert_arn.random_uuid.uuid`

**Comment by matti** [comment]
thanks, I try to reproduce soon

**Comment by matti** [comment]
Can you share a repo that would allow me to see this in action?

**Comment by matti** [comment]
archiving this project in favor of https://github.com/Invicton-Labs/terraform-external-shell-resource and https://github.com/Invicton-Labs/terraform-external-shell-data
