### ISSUE TITLE
setting this module to depend_on another resource

### ISSUE THREAD

**Issue by discentem** [matti/terraform-shell-resource#3]
How can I only run this module after another resource already exists?

**Comment by matti** [comment]
Hi @discentem! Maybe with var.depends_id, can you share some code?

**Comment by discentem** [comment]
Hi @matti! 👋 

So, I'm trying to use the module to run a shell command but I need to ensure another resource (which creates a server) finishes first or else my shell command will fail. 

```
module "stdout_output_path" {
  source = "./terraform-shell-resource/"
  command = "python script.py --arg1 stuff ..."
}
output "stuff" {
  value = {
    stdout = "${module.stdout_output_path.stdout}"
    stderr = "${module.stdout_output_path.stderr}"
    exitstatus = "${module.stdout_output_path.exitstatus}"
  }
}
```

Can I set the module to depend on another resource? something like:

```
module "stdout_output_path" {
  source = "./terraform-shell-resource/"
  command = "python script.py --arg1 stuff ..."
  depends_on = "google_compute_instance.Thing"
}
```

Also, a less important question, can I name the "module" in my code something other than "stdout_output_path"?

**Comment by matti** [comment]
yes, just use `depends_id` instead of `depends_on`

I didn't want to use `depends_on` because it is kinda reserved... but maybe I should.

And yes, you may name your instance of the module however you wish - this is how terraform modules work in general.

Let me know if this works.

**Comment by matti** [comment]
@discentem?

**Comment by discentem** [comment]
Hey @matti, sorry! I haven't been able to circle back to this yet.

**Comment by jamesc** [comment]
Just ran into this.  The syntax that works for me is:

```
  depend_id="${google_compute_instance.Thing.id}"
```

**Comment by matti** [comment]
@jamesc I believe you have to use that `depend_id` somehow? Just by that it does not do anything.

**Comment by jamesc** [comment]
Sorry, yep - here's the full example.  to key to me getting it work was to use the ID, not the instance of the resource.

```
module "stdout_output_path" {
  source = "matti/resource/shell"
  command = "python script.py --arg1 stuff ..."
  depends_id = "${google_compute_instance.Thing.id}"
}
```

**Comment by matti** [comment]
@jamesc are you sure that it's `depend_id` and not `depends_id` that works for you?

**Comment by matti** [comment]
@jamesc ?

**Comment by jamesc** [comment]
@matti Sorry, you're right - typo in the example above - `depends_id`.  Here's an example: https://github.com/chef-partners/chef-automate-tf/blob/master/aws/chef_automate/automate_server.tf#L98-L102

**Comment by matti** [comment]
Cool!
