### ISSUE TITLE
This only works on Linux, right?

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [matti/terraform-shell-resource#30]
Usually when running terraform modules, I have an expectation that they are usually client-independent. I didn't see anything in the README that said otherwise at least.

However, since this module makes heavy use of shell scripts, I assume it only runs on Linux distributions. When I try running it on windows (even in a linux shell), I get a `"%1 is not a valid Win32 application."` error.

Is there a way to run this module on Windows, or at least achieve a similar effect?

**Comment by matti** [comment]
This only works on linux. It is possible to add support for windows, but I don't have any interest in windows.

**Comment by nadworny** [comment]
it would probably make sense to mention it in README :)

**Comment by matti** [comment]
PR welcome

**Comment by KyleKotowick** [comment]
I just created a PR for Windows support. #36

**Comment by matti** [comment]
thanks, I have no way of testing this - I'd like to wait for some confirmation before I release this from master

**Comment by matti** [comment]
released
