### ISSUE TITLE
 Parameter is incorrect-- help wanted

### ISSUE THREAD

**Issue by Suresh8811** [matti/terraform-shell-resource#39]
Hi,

I am getting this error. Could someone please let me know what might be the issue.

Error: Error running command 'aws workmail create-organization --directory-id d-936708d5a3 --alias learning --region eu-west-1': fork/exec C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe: The parameter is incorrect.. Output:

![shell_resource](https://user-images.githubusercontent.com/40217330/124154283-418dfb80-da8d-11eb-9702-22b2f2ebb3b1.PNG)

**Comment by KyleKotowick** [comment]
Handled in #40

**Comment by matti** [comment]
merged #40

**Comment by matti** [comment]
archiving this project in favor of https://github.com/Invicton-Labs/terraform-external-shell-resource and https://github.com/Invicton-Labs/terraform-external-shell-data
