### ISSUE TITLE
Proposal: rename the repository

### ISSUE THREAD

**Issue by KyleKotowick** [matti/terraform-shell-resource#41]
I'd like to propose that the repository be renamed to `terraform-external-shell-resource`. 

This follows Terraform's suggested convention of `terraform-{provider}-{name}`, and `external` is the appropriate name for the provider (from the [external doc page](https://registry.terraform.io/providers/hashicorp/external/latest/docs), which states that "`external` is a special provider that exists to provide an interface between Terraform and external programs.")

**Comment by matti** [comment]
sounds good, although I think this should be rewritten as a provider because this is a horrible hack

**Comment by matti** [comment]
archiving this project in favor of https://github.com/Invicton-Labs/terraform-external-shell-resource and https://github.com/Invicton-Labs/terraform-external-shell-data
