### ISSUE TITLE
April enhancements not available via the Terraform Registry

### ISSUE THREAD

**Issue by robertpeteuil** [matti/terraform-shell-resource#5]
This is an awesome module - thanks for sharing!

Can you submit a new release?   The version available via the Terraform Registry doesn't include the improvements you made in April as it only refreshes on GitHub releases.

**Comment by matti** [comment]
uuh, good point - should setup CI/CD pipeline. I'll do this soon.

**Comment by matti** [comment]
@robertpeteuil sorry it took a while - no need to setup CI/CD actually, just push the tags..
