### ISSUE TITLE
exitstatus & stdout file resources re-created during second run when module not triggered

### ISSUE THREAD

**Issue by robertpeteuil** [matti/terraform-shell-resource#6]
I just noticed an odd behavior & I'm not sure if this is a known limitation or something that can be fixed.

- When using the module with a trigger everything works as expected on the first execution
- On the second run of `apply` the module recreates files for existstatus & stdout (even though they already exist)
  - This is problematic when running `apply` as it displays resources created when nothing has changed (which can trip up CI runs):
- The odd part is that subsequent `apply`, after the second, no longer exhibits this behavior.

Here's how I'm calling the module (using the sha of a file as a trigger and calling a script and passing the file as an argument):

``` ruby
module "create_func_zip" {
  source  = "git::https://github.com/matti/terraform-shell-resource"
  trigger = "${base64sha256(file("src/function.py"))}"
  command = "./build.sh -f src/function.py"
}
```

- As stated - all work as expected the first `apply`
- Running `terraform plan` a second time, after its been applied, shows the plan below. (and apply makes the changes).

``` bash
Terraform will perform the following actions:
<= module.builder.module.create_func_zip.data.local_file.exitstatus
     filename: "/Users/me/code/tf/builder/.terraform/modules/00218911b30963c1b7d950cc9df57fe9/exitstatus.130084382878536778"
<= module.builder.module.create_func_zip.data.local_file.stderr
     filename: "/Users/me/code/tf/builder/.terraform/modules/00218911b30963c1b7d950cc9df57fe9/stderr.130084382878536778"
<= module.builder.module.create_func_zip.data.local_file.stdout
     filename: "/Users/me/code/tf/builder/.terraform/modules/00218911b30963c1b7d950cc9df57fe9/stdout.130084382878536778"

+ module.builder.module.create_func_zip.local_file.exitstatus
     filename: "/Users/me/code/tf/builder/.terraform/modules/00218911b30963c1b7d950cc9df57fe9/exitstatus.130084382878536778"
+ module.builder.module.create_func_zip.local_file.stdout
     filename: "/Users/me/code/tf/builder/.terraform/modules/00218911b30963c1b7d950cc9df57fe9/stdout.130084382878536778"

Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by matti** [comment]
@robertpeteuil hey, I just created a repro of this here https://github.com/matti/repro-terraform-shell-resource-6

The logic behind this hack is so complex that I have to have atleast 10x 🍺 to understand what is happening here - are you able to workaround this somehow?

**Comment by matti** [comment]
I think I just came up with a fix, have to test more though. Looks we could just use `file` + `depends_on`

```
resource "null_resource" "contents" {
  depends_on = ["null_resource.shell"]

  triggers = {
    stdout     = "${file("${path.module}/stdout.${null_resource.start.id}")}"
    stderr     = "${file("${path.module}/stderr.${null_resource.start.id}")}"
    exitstatus = "${file("${path.module}/exitstatus.${null_resource.start.id}")}"
  }

  lifecycle {
    ignore_changes = [
      "triggers",
    ]
  }
}
```

**Comment by matti** [comment]
https://github.com/matti/terraform-shell-resource/pull/10/files

**Comment by matti** [comment]
nope - looks like before terraform 0.12 the only option would be to disable "trigger" support completely

**Comment by matti** [comment]
trigger support doesn't even work properly - the command is executed, but the output is not updated (because of the lifecycle ignore_changes hack)

**Comment by matti** [comment]
released a new version that does not create files on second apply, but opened another issue on the outputs #12
